# Generated by Django 2.2.5 on 2019-09-27 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('school_short_name', models.CharField(max_length=70)),
                ('school_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('school_contact', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('school_mobile', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school/school_logo/%y %m %d')),
                ('district', models.CharField(max_length=255)),
                ('tehsil', models.CharField(max_length=255)),
                ('demo_video', models.FileField(blank=True, null=True, upload_to='school/videos/')),
                ('school_address', models.CharField(blank=True, max_length=255, null=True)),
                ('slogan', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=1500, null=True)),
                ('principal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('principal_qual', models.CharField(blank=True, max_length=255, null=True)),
                ('principal_pic', models.ImageField(blank=True, null=True, upload_to='school/principal/%y %m %d')),
                ('principal_message', models.TextField(blank=True, max_length=700, null=True)),
                ('school_slider1', models.ImageField(blank=True, null=True, upload_to='school/slider/%y %m %d')),
                ('school_slider2', models.ImageField(blank=True, null=True, upload_to='school/slider/%y %m %d')),
                ('school_slider3', models.ImageField(blank=True, null=True, upload_to='school/slider/%y %m %d')),
                ('school_slider_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('school_slider_desc', models.TextField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=55)),
                ('teacher_qual', models.CharField(max_length=255)),
                ('teacher_intro', models.TextField(max_length=3000)),
                ('teacher_img', models.ImageField(upload_to='teachers/%y %m %d')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_heading', models.CharField(max_length=255)),
                ('news_desc', models.TextField(max_length=2500)),
                ('image', models.FileField(upload_to='news/%Y %m %d/')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('published_by', models.CharField(choices=[('AD', 'Admin'), ('SU', 'Supervisor')], max_length=2)),
                ('news_category', models.CharField(choices=[('LA', 'Latest'), ('AD', 'Admission'), ('RS', 'Result'), ('AB', 'About'), ('PR', 'Principal message'), ('OT', 'other')], max_length=2)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_img_title', models.CharField(max_length=30)),
                ('gallery_img', models.ImageField(upload_to='gallery/%y %m %d')),
                ('img_category', models.CharField(choices=[('LB', 'LAB'), ('CM', 'Classroom'), ('LR', 'Library'), ('CA', 'CAFE'), ('OT', 'Others')], max_length=2)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
    ]
