# Generated by Django 2.2.5 on 2019-09-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='facebook_addr',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='gmail_id',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='linkedin_addr',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='twitter_addr',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='facebook_addr',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gmail_id',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='linkedin_addr',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='twitter_addr',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='district',
            field=models.CharField(choices=[('AB', 'Abbottabad'), ('BN', 'Bannu'), ('BG', 'Battagram'), ('CR', 'Charsada'), ('NS', 'Dera Ismail Khan'), ('HN', 'Hangu'), ('HR', 'Haripur'), ('KR', 'Karak'), ('KT', 'Kohat'), ('LK', 'Lower Kohistan'), ('MA', 'Mansehra'), ('MR', 'Mardan'), ('MM', 'Momand'), ('NS', 'Nowshera'), ('PS', 'Peshawar'), ('SB', 'Sawabi'), ('TG', 'Torgar'), ('UK', 'Upper Kohistan')], max_length=2),
        ),
        migrations.AlterField(
            model_name='school',
            name='tehsil',
            field=models.CharField(max_length=25),
        ),
    ]
