# Generated by Django 2.2.5 on 2019-09-29 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20190930_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='gmail_id',
        ),
    ]
