# Generated by Django 2.2.5 on 2019-10-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_school_gmail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='achievements',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='environment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='teacher_expertise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
